branch-defaults:
  master:
    environment: My-portfolio-django-app-env
environment-defaults:
  My-portfolio-django-app-env:
    branch: null
    repository: null
global:
  application_name: my-portfolio-django-app
  default_ec2_keyname: null
  default_platform: Python 3.13
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
